# Generated by Django 2.2.7 on 2020-09-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='customer_name',
        ),
    ]
